### ISSUE TITLE
Migrations not Included

### ISSUE THREAD

**Issue by kaffineaddict** [Beskhue/CookieTokenAuth#18]
Release 1.2.0 does not include the migrations files needed for migrate to run successfully.

**Comment by tomcur** [comment]
That's right. Version 1.2.0 does not have migrations defined. Sorry! Instead, you need to manually execute the code in [db.sql](https://github.com/Beskhue/CookieTokenAuth/blob/1.2.0/db.sql).

The master branch has migrations defined, though no release containing them has been made yet.
