### ISSUE TITLE
setCookie() is not executed in README example

### ISSUE THREAD

**Issue by janmuennich** [Beskhue/CookieTokenAuth#2]
In README this is in AppController's beforeFilter:

```
if(!$this->Auth->user())
{
    $user = $this->Auth->identify();
    if ($user) {
        $this->Auth->setUser($user);
        return $this->redirect($this->Auth->redirectUrl());
    } 
}  

```

This code will be executed for Cookie and Form logins. With Form logins, redirect() prevents the code in UserController's login() from being run where setCookie() is called.

So I changed the code in AppController to:

```
if(!$this->Auth->user())
{
    $user = $this->Auth->identify();
    if ($user) {
        $this->Auth->setUser($user);
        if ($this->request->params['controller'] != 'Users' && $this->request->params != 'login' && !$this->request->is('post')) {
            return $this->redirect($this->Auth->redirectUrl());
        }
    } 
}  
```

And the code in UsersController to:

```
public function login()
{
    $this->loadComponent('Beskhue/CookieTokenAuth.CookieToken');

    if ($this->request->is('post')) {
        $user = $this->Auth->user();
        if ($user) {
            $this->CookieToken->setCookie($user);
            return $this->redirect($this->Auth->redirectUrl());
        } else {
            $this->Flash->error(__('Username or password is incorrect.'));
        }
    }
}
```

This is definitely not elegant. Maybe you have a better idea for that.

**Comment by tomcur** [comment]
What version of CakePHP are you using? I am not able to reproduce this issue in version 3.2.7. In 3.x, `redirect` should not exit. While the README example returns out of `beforeFilter`, the login action should still be called: http://book.cakephp.org/3.0/en/controllers.html#redirecting-to-other-pages

**Comment by janmuennich** [comment]
I have the issue with 3.3.x. `return $this->redirect()` prevents login() from being executed.

**Comment by tomcur** [comment]
I will create a 3.3.x install soon to test this.

**Comment by tomcur** [comment]
I didn't have much time for development previous weeks, so I just now tested this on CakePHP 3.3.5. I am still not able to reproduce this issue. 

If I perform a form login, `redirect` is called and subsequently `UsersController->login()` is still called. You can add a `die()` right after the redirect in `AppController` to see if the redirect truly is stopping execution and is redirecting immediately.

**Comment by tomcur** [comment]
Please tell me if you still have this issue.
