### ISSUE TITLE
[FIX INSIDE] - Bug when logout

### ISSUE THREAD

**Issue by cyberbobjr** [Beskhue/CookieTokenAuth#6]
Hi,
if you logout the user, you'll have an error of "index "userModel" undefined".
The fix is to add the config array to the TableRegistry::get of "logout function" inside your component.

in CookieTokenAuthenticate :
before 
````
$authTokens = \Cake\ORM\TableRegistry::get('Beskhue/CookieTokenAuth.AuthTokens');
````

after 
````
$authTokens = \Cake\ORM\TableRegistry::get('Beskhue/CookieTokenAuth.AuthTokens',
                                                   ['userModel' => $this->_config['userModel']]);
````

**Comment by cyberbobjr** [comment]
One more :
in "CookieTokenComponent"
```
    public function setCookie($user, $token = NULL)
    {
        $authTokens = \Cake\ORM\TableRegistry::get('Beskhue/CookieTokenAuth.AuthTokens',
                                                   ['userModel' => $this->_config['userModel']]);

```

But beware to put the userModel config when you load the component 
```
        $this->loadComponent('Beskhue/CookieTokenAuth.CookieToken', ['userModel' => 'UserManager.Users']);
```

**Comment by tomcur** [comment]
Thank you for your reports. 

Once I started working on your initial issue I noticed the second issue you just mentioned as well. They're fixed locally already and I will push the commits shortly.

I'm rewriting the plugin slightly such that users no longer need to load and use `CookieTokenComponent` manually. That way, plugin configuration is performed fully through `AuthComponent`, and all configuration is in a single place. This is also more robust if a variety of authentication adapters are used.

**Comment by cyberbobjr** [comment]
Hi,
Thanks for your answer, i'm trying to use your *must have* component, but i have some troubles :(
I followed the readme, but when i'm trying to log in, i have these error :
```
Notice (8): Undefined index: userModel [ROOT/vendor/beskhue/cookietokenauth/src/Controller/Component/CookieTokenComponent.php, line 29]
Code Context
Beskhue\CookieTokenAuth\Controller\Component\CookieTokenComponent::setCookie() - ROOT/vendor/beskhue/cookietokenauth/src/Controller/Component/CookieTokenComponent.php, line 29
UserManager\Controller\UsersController::login() - ROOT/plugins/UserManager/src/Controller/UsersController.php, line 249
```

this is my code where the error was raised :
```
if ($this->request->is('post')) {
            // On identifie l'utilisateur avec les paramètres fournis par la requête POST
            $user = $this->Auth->identify();
            if (!$user) {
                // les credentials ne sont pas corrects, nous affichons une erreur
                $this->Flash->error(__('Login ou mot de passe incorrect.'));
                // et nous envoyons un événement système "login failure"
                $event = new Event('User.Login.Failure', $this, ['request' => $this->request]);
                $this->eventManager()
                     ->dispatch($event);
            } else {
                $this->loadComponent('Beskhue/CookieTokenAuth.CookieToken');

                $this->CookieToken->setCookie($user);
...
```

It's really strange.
I digged inside the source code, but i don't understand this :
```
    public function redirectToAuthenticationPage($url = NULL)
    {
        if ($url) {
            $this->Auth->redirectUrl($url);
        } else {
            $this->Auth->redirectUrl($this->request->here(FALSE));
        }

        $this->controller->redirect(Router::url(['plugin'     => 'Beskhue/CookieTokenAuth',
                                                 'controller' => 'CookieTokenAuth',
                                                 'prefix'     => FALSE,
                                                 '_base'      => FALSE]));
    }
```
because the $url parameter is always null, and the "index" function of the "CookieTokenAuth" controller is a blank page :(

Please can you explain me ?
Many thanks
Regards

**Comment by tomcur** [comment]
Hey,

I've pushed the fixes and released a new version of the plugin. I believe this should fix your issues.

Note that in the new version you probably no longer need the following code:

```
$this->loadComponent('Beskhue/CookieTokenAuth.CookieToken');

$this->CookieToken->setCookie($user);
```

CookieTokenAuth now automatically handles `afterIdentify` events created by, e.g., FormAuthenticate.

**Comment by tomcur** [comment]
I believe updating to the latest version (1.0.0) will solve your issues, so I'm closing this. If it doesn't, please comment.
