### ISSUE TITLE
Error: Missing Route

### ISSUE THREAD

**Issue by ArakTaiRoth** [Beskhue/CookieTokenAuth#7]
I'm setup the plugin in a CakePHP 3 project as described in the readme. I'm getting an error when I go to the first page of my application, which doesn't require a user to be logged in (ie. It's open to everyone).

Error: A route matching "array ( 'controller' => 'Portfolios', 'action' => 'view', '_base' => false, 'plugin' => 'Beskhue/CookieTokenAuth', '_ext' => NULL, )" could not be found.

More data as follows:

None of the currently connected routes match the provided parameters. Add a matching route to config/routes.php

The passed context was:

[
	'_base' => '',
	'_port' => '80',
	'_scheme' => 'http',
	'_host' => 'localhost',
	'params' => [
		'plugin' => 'Beskhue/CookieTokenAuth',
		'controller' => 'CookieTokenAuth',
		'action' => 'index',
		'_ext' => null,
		'pass' => [],
		'_matchedRoute' => '/auth/cookie-token-auth'
	]
]

**Comment by tomcur** [comment]
Hi ArakTaiRoth,

Thank you for your report.

Can you confirm your `bootstrap.php` contains the following line exactly?

```
Plugin::load('Beskhue/CookieTokenAuth', ['routes' => true]);
```

It sounds like it already does. Instead, especially if you have CakePHP 3.4, you might want to try CookieTokenAuth version 1.1.0 that I just released. It has better support for redirecting in CakePHP 3.4.

**Comment by ArakTaiRoth** [comment]
Yes, bootstrap.php does indeed include that line. I tried your suggestion of updating CookieTokenAuth, and now I'm getting a different issue. Basically I'm seeing an infinite redirect loop. I request localhost, and get redirected to http://localhost/auth/cookie-token-auth?redirect=%2F, which then redirects me back to localhost, and we continue.

**Comment by tomcur** [comment]
That's odd. After upgrading to 1.1.0, have you tried closing and re-opening your browser, just to be safe? It sounds like a session cookie is not set or read properly.

**Comment by ArakTaiRoth** [comment]
Yes, I have cleared all cookies and also tried in Incognito Mode in Chrome, both resulted in the same error being shown.

**Comment by ArakTaiRoth** [comment]
After some further testing, I found the real error (all this was a red herring), I was using the SessionHelper, which has been deprecated, but I didn't know until I ran composer update to get this Plugin in my codebase. Everything appears to be working now. I still have to test that this plugin is doing what I need it to do, but at the very least I have no blatant errors anymore.

Sorry to have wasted your time.

**Comment by ArakTaiRoth** [comment]
So, I was wrong, this is still an issue, with the infinite redirect loop. I sat down to actually test that it was doing what I expected it to do. So I logged in, and then closed the tab without logging out, expecting it to keep my token alive and allowing me to just go back to any page.

I got the infinite redirect loop instead, so I did some debugging, and first thing that struck me as odd was that it didn't find my user during `$user = $this->Auth->identify()` in the AppController `beforeFilter()`. I kept digging, and I believe the problem resides within the CookieTokenAuthenticate.php file, but I'm not sure why.

Line 26 has `if ( !$this->authenticateAttemptedThisSession($request))`, which checks if `CookieTokenAuth.attempted` has been set for the session, and if it has, do nothing as we've already checked. I have verified this is being set, but on redirect back to the main page `/`, it's gone, and so the loop repeats.

![image](https://cloud.githubusercontent.com/assets/1081991/25370201/4c3e2570-2946-11e7-9fac-b08baa0a3d19.png)
![image](https://cloud.githubusercontent.com/assets/1081991/25370211/5eec3d1a-2946-11e7-902f-f9883474d412.png)

**Comment by tomcur** [comment]
Thank you for investigating this. 

I'll have an in depth look in four hours or so. 

In the meantime, could you tell me whether you have a custom user model or database schema? 

And is `afterIdentify` in `CookieTokenAuthenticate.php` called with data you expect in `$user`?

**Comment by tomcur** [comment]
To be clear, `afterIdentify` should be called after you log in to a user. This should be done automatically for form logins. See "create token cookies" in the readme.

**Comment by ArakTaiRoth** [comment]
I have a slightly customer schema. I use an email column for username:

```
$this->loadComponent('Auth', [
				'authorize' => ['Controller'],
				'authenticate' => [
					'Beskhue/CookieTokenAuth.CookieToken' => [
						'fields' => [
							'username' => 'email',
							'password' => 'password'
						]
					],
					'Form' => [
						'fields' => [
							'username' => 'email',
							'password' => 'password'
						]
					]
				],
```

I can't test the afterIdentify issue though until I resolve this infinte loop. But will be happy to share that with you once this issue is resolved. I appreciate the time you're taking on this.

**Comment by tomcur** [comment]
So far I've verified that your schema works, so the issue lies elsewhere.

When you log in to the user using the login form, is a token created and inserted into the `auth_tokens` table in your database?

If so, check the following things:
1. is the `user_id` field correct? It should refer to the user you initially logged in with.
2. if you close and open the browser, and browse to your site (thus attempting to use the token cookie), does the `token` field of the database entry change? It should change every time the session is refreshed through use of the token cookie.

**Comment by ArakTaiRoth** [comment]
The problem is I can't test any of that at the moment because I can't get past the infinite redirect loop. The only way past the infinite redirect loop is to remove the link to the CookieTokenAuth plugin, which means I wouldn't be able to test any of that anyways.

I do know that there was 2 entries in the auth_tokens table for my user that I had previously logged in as.

**Comment by tomcur** [comment]
Currently you're not even able to visit the site after clearing cookies? You immediately get stuck in the loop?

I think the issue is caused by something going wrong in handling of cookies and sessions by either your CakePHP installation or your browser. I am not sure whether the CookieTokenAuth plugin triggers this issue, or whether it's caused by something else.

I think this, because the `CAKEPHP` response cookie (which is the CakePHP session), sent by your site on the `localhost/auth/cookie-token-auth` page, is not sent as a request cookie by your browser on the subsequent request to `localhost`. It seems that the session cookie is simply getting ignored by your browser.

When you disable the plugin, is logging in possible, and are you able to browse the site, whilst staying logged in?

**Comment by ArakTaiRoth** [comment]
Yes, if I remove the plugin from being loaded, the site functions as I would expect it to when logging in. I have tested the plugin in other browsers, and you are absolutely accurate, this only happens in Chrome for me. I'm not sure why, as I have very little configuration done to this browser to make it "unique".

But this still worries me because this is potentially something that users of the site could then run into.

**Comment by tomcur** [comment]
It worries me too.

What version of Chrome are you using? Chrome on my installation does not exhibit this problem, but I'll attempt to recreate the issue. It seems to be a common problem with Chrome, see e.g. http://blog.pixelastic.com/2011/04/13/losing-session-request-cakephp-chrome/, it also happens with other frameworks and Chrome.

**Comment by ArakTaiRoth** [comment]
I am using version 57.0.2987.133

**Comment by tomcur** [comment]
Oops, accidentally closed the issue. Re-opened :-) I'll see whether I can reproduce the issue, but probably can't get to it until sometime next week. Thank you for all the information so far.

**Comment by ArakTaiRoth** [comment]
One thing to maybe take note of, I have my Session set up thusly:

```
'Session' => [
        'defaults' => 'php',
        'ini' => [
          'session.cookie_secure' => TRUE
        ]
    ],
```

I'll also keep looking into this and let you know anything that I find.

**Comment by tomcur** [comment]
I'll try that configuration soon, to test whether it's the culprit.

**Comment by ArakTaiRoth** [comment]
So, based on that link you sent, I modified my session configuration to include what the fix said would work:

```
'Session' => [
		'defaults' => 'php',
		'ini' => [
			'session.cookie_lifetime' => 525600,
			'session.cookie_path' => '/',
			'session.cookie_secure' => TRUE,
			'session.name' => 'STOCKERS',
			'session.referer_check' => '',
			'session.use_trans_sid' => 0
		],
	],
```

It did not work.

**Comment by tomcur** [comment]
Your CakePHP configuration with `'session.cookie_secure' => TRUE` works fine for me.

I was able to reproduce your issue, but only through changing a setting in Chrome:

`chrome://settings` -> Show advanced settings -> Privacy -> Content settings -> Cookies -> Block sites from setting any data.

Many other sites still work fine, even with that setting turned on. Can you confirm this is set in your Chrome configuration?

**Comment by ArakTaiRoth** [comment]
I wish that were the case, I can confirm it is not set on my end.
![image](https://cloud.githubusercontent.com/assets/1081991/25454351/641cc626-2a89-11e7-9cd6-7c1614eb894d.png)

**Comment by tomcur** [comment]
Do you have any Chrome extensions that might interfere with cookies/tracking?

**Comment by ArakTaiRoth** [comment]
I did think of that and went through and disabled all extensions that I have, the problem still persists. I also went through all of my settings, and I have nothing anywhere that is changed from the default or recommended values.

**Comment by tomcur** [comment]
I'm still not able to reproduce the issue... With what webserver are you hosting the site? And you're browsing with Chrome on Windows?

**Comment by ArakTaiRoth** [comment]
I can duplicate the issue with both Chrome and Firefox. I can not duplicate the issue with Edge.

This is being run using a docker container. I believe the container is using Apache on a CentOS distribution. I am testing locally on my machine.

**Comment by ArakTaiRoth** [comment]
I recently pushed this to AWS to see if it was just me experiencing the issue. However, the entirety of the code works just fine on AWS, until I add the authenticate option using Beskhue/CookieTokenAuth.CookieToken. As soon as I add that, the load balancers health checks fail and all I get back are 503 errors when trying to visit, so this definitely is not just contained to my system or browsers, this must be something with how Cake is configured for me.

So here's the rest of my configuration in AppController, this is how Cookies and Security are implemented for me, maybe this will help narrow down the issue:

```
$this->loadComponent('Csrf', ['secure' => TRUE]);
$this->loadComponent('Security', ['blackHoleCallback' => 'forceSSL']);
$this->loadComponent('Cookie', [
	'secure' => TRUE,
	'httpOnly' => TRUE
]);
```

**Comment by ArakTaiRoth** [comment]
Have you made any progress looking into this? I haven't been able to find anything else myself, just that the issue can be found in other areas by other users and on multiple browsers. The only thing linking all the areas is the server setup and the cake installation. I'm running CakePHP 3.4.5, CentOS 6.8, and PHP 5.6.

**Comment by tomcur** [comment]
Thank you for the additional information. I haven't been able to make more progress as I'm currently away, but I'll pick this up again in three days. 

This is important to me, so I'm trying hard to fix the issue.

**Comment by tomcur** [comment]
I am now able to reproduce this issue using the following configuration in `app.php` when accessing the site over HTTP (as opposed to HTTPS):

```
'Session' => [
        'defaults' => 'php',
        'ini' => [
          'session.cookie_secure' => TRUE
        ]
    ],
```

I am not yet sure why it worked before, but I probably made a mistake somewhere.

The issue presents itself in Firefox, Chrome and also Edge for me. I think it is purely a configuration issue; using `'session.cookie_secure' => TRUE` indicates all cookies sent by CakePHP will get the `SECURE` flag in the cookie header sent by the server. Read more about that flag [here](https://tools.ietf.org/html/rfc6265#section-4.1.2.5). 

In short, the secure flag means cookies set by the server will only be sent back by the browser over HTTPS (even if they were set by the server over HTTP).

In specific importance to us, this means the site will only function when accessed entirely over HTTPS, as when accessing it over HTTP the session is not kept track of properly: it requires cookies to be sent by the browser to keep track of the session, but the browser is not doing that. Thus the client gets stuck in an infinite redirect loop over HTTP.

Do you have HTTPS configured? If so, you should probably add a redirect (perhaps in Apache) from HTTP to HTTPS. Perhaps you already had internal links on the website configured to send users to HTTPS, which would explain why your site works (including logging in) without the plugin. The site should also work if you visit over HTTPS manually, instead of HTTP.

In any case, if all this is correct, we can also change the configuration instead of adding the HTTP -> HTTPS redirect. Setting the following in `app.php` should work, though it would be less secure:

```
'Session' => [
        'defaults' => 'php',
    ],
```

i.e., remove `session.cookie_secure' => TRUE`.

**Comment by tomcur** [comment]
I'll also add a configuration option disabling the redirect necessity of the plugin. This will only minimally reduce security; currently, the redirect is in place to ensure the token cookie is only sent once per session, instead of each request.

**Comment by tomcur** [comment]
The token cookie exposure minimization, and thus the redirect behavior, can be disabled as of version 1.2.0.

```
$this->loadComponent('Auth', [
    'authenticate' => [
        'Beskhue/CookieTokenAuth.CookieToken' => [
            'fields' => [
                'username' => 'email',
                'password' => 'password',
        ],
        'minimizeCookieExposure' => false,
    ],
],
```

Please let me know if this or the HTTP -> HTTPS redirect resolves the issue.

**Comment by ArakTaiRoth** [comment]
So, I looked a little bit into this. I believe you are correct on your findings. I don't run over HTTPS on my local machine, and we only run HTTPS to our load balancer, from the load balancer to the actual instance we run over HTTP, as contained in the same network, there's little need (as far as I understand) to maintain security, I could be wrong about that though.

Your option did indeed work, with one minor change:
```
$this->loadComponent('Auth', [
    'authenticate' => [
        'Beskhue/CookieTokenAuth.CookieToken' => [
            'fields' => [
                'username' => 'email',
                'password' => 'password'
            ],
            'minimizeCookieExposure' => false
        ]
    ],
```

Just a question regarding your fix. What exactly are the potential security implications of implementing it this way? And are there any performance implications?

**Comment by tomcur** [comment]
Great that it works!

There is one remaining thing I find odd, mostly unrelated to the plugin. As you have configured `'session.cookie_secure' => TRUE`, I would expect the website and browser not to be able to handle any sessions nor permanent logins over HTTP, as the browser would not send cookies over HTTP. It seems to me that with that configuration the website should **only** work correctly over HTTPS. However, I'm not familiar with AWS and the load balancer might change things. It's just odd that the plugin's once-per-session redirect doesn't work but logging in does work, even though they both use the same CakePHP session mechanism to keep track of the client.

# Security
The potential security implications of disabling token cookie minimization are minimal. By not minimizing the cookie exposure, the token cookie will be sent on each page visit as opposed to just once per session. This simply makes it slightly more practical for an eavesdropper to steal the cookie. This is basically only possible over HTTP though, as over HTTPS the cookie would also be encrypted through SSL.

However, even over HTTP, the cookie itself is additionally encrypted by CakePHP, and only your CakePHP instance has the key to decrypt it. If an eavesdropper does succeed in decrypting it, they would find two (random) strings: a series string and a token string, these are linked to the user through the database. They would not know the user's password.

Though, without decrypting the token cookie, the attacker would be granted access to the user's account. Stealing a CakePHP session cookie would grant the same access, but on a shorter scale. So it's just the persistance of token cookies that cause the minimal additional security risks.

But, in the event that both the user and the attacker attempt to use the same token cookie -- which is likely to happen, as the attacker **stole** the cookie without the user's knowledge -- one of the two token cookies would be deemed invalid. Remember that the token cookie consists of a series and a token; each time a series is used (once per session), the token is updated. If a token cookie is presented with a known series, but has a wrong (stale) token, all the corresponding user's token cookies are invalidated, causing the attacker to be locked out until a new token cookie is stolen.

Remember that all this is basically just an issue over HTTP, but over HTTP there are many other security issues anyway; for instance, when a user logs in, their username and password are sent in plaintext over the network. But so long as you trust all parts of the network where stuff is not encrypted, it should be fine.

# Performance
Minimizing token cookie exposure increases the initial site load time at the start of a session, as a user is redirected twice at the start; first to the authentication page, and then back. Disabling the token cookie exposure minimization the performance increases for the first visit of the session.

**Comment by ArakTaiRoth** [comment]
Awesome, this all looks good to me then. Everything from the user to the server is sent over HTTPS, it's just from the load balancer to the instance that it is sent over HTTP, which is all on the same network, so it's secure, as they would have to gain access to the network to see it, which if that was the case we would have much larger problems.

Thank you very much for your time spent on this issue and resolving it quite quickly for me, I greatly appreciate it.

**Comment by tomcur** [comment]
I'm glad this solves the issue! Thank you for reporting it, and for sticking with the difficult debug process.
